source ~/.local/zshuery/zshuery.sh
load_defaults
load_aliases
load_lol_aliases
load_completion ~/.local/zsh-completions
load_correction

prompts '%{$fg_bold[green]%}$(COLLAPSED_DIR)%{$reset_color%}$(virtualenv_info) %{$fg[yellow]%}$(prompt_char)%{$reset_color%} ' '%{$fg[red]%}$(ruby_version)%{$reset_color%}'

chpwd() {
	update_terminal_cwd
}
